### ISSUE TITLE
reprodure issues

### ISSUE THREAD

**Issue by peylnog** [stevewongv/SPANet#11]
hello , i have a question , how can i reproduce your  model by my datasets  ? thanks a lot

**Comment by stevewongv** [comment]
> hello , i have a question , how can i reproduce your  model by my datasets  ? thanks a lot

You can directly train the model with your data. But make sure the masks are good. Ps. You can stop at 50k-60k iterations.

**Comment by peylnog** [comment]
I am so sorry ， I didn't read your papers carefully. ，sorry ， Can you describe it in detail? my datasets just have two parts ， rain and clear ， thanks again.

**Comment by stevewongv** [comment]
> I am so sorry ， I didn't read your papers carefully. ，sorry ， Can you describe it in detail? my datasets just have two parts ， rain and clear ， thanks again.
> 
> 

Read the paper first. Thanks.
