### ISSUE TITLE
Change the path and PSNR of the training and test datasets

### ISSUE THREAD

**Issue by FUNGERN** [stevewongv/SPANet#12]
Thank you for your contribution, I have finished reading your thesis, and now using your code, I find that I can't find in which .py file to change the path of the training dataset and test dataset, if you know please tell me. In addition, I found that the evaluation does not have a PSNR code. Could you post it? thank you.

**Comment by FUNGERN** [comment]
> Thank you for your contribution, I have finished reading your paper, and now using your code, I find that I can't find in which .py file to change the path of the training dataset and test dataset, if you know please tell me. In addition, I found that the evaluation does not have a PSNR code. Could you post it? thank you.

**Comment by stevewongv** [comment]
For path, you can generate a path.txt to replace the original one. The format is like:
```
./image_path1.png ./gt1.png
./image_path2.png ./gt2.png
```
**Please make sure that the mask should be precise!**

For PSNR: https://github.com/stevewongv/SPANet/blob/e97af62dce976b9e73ae94f03c58491a456f6dc2/main.py#L278

**Comment by stevewongv** [comment]
For changing the path.txt file, please revise the line in main.py:
https://github.com/stevewongv/SPANet/blob/e97af62dce976b9e73ae94f03c58491a456f6dc2/main.py#L56

**Please read the code carefully.**

**Comment by FUNGERN** [comment]
@stevewongv Thank you for your answer. Is a photo corresponding to its GT? Is it separated by a space? Or can I do the replacement directly in the .txt you have generated? Or can you tell me a faster and better way?

**Comment by stevewongv** [comment]
Using a python script to generate the txt file is the fast way. Yes, it is separated by a space.

**Comment by FUNGERN** [comment]
Thank you for your answer. Could you post Python code on your Github？

**Comment by stevewongv** [comment]
You can write it by yourselves... It's just a simple script. I have deleted all the files due to the limited storage.

**Comment by FUNGERN** [comment]
@stevewongv Thank you for your reply, I have solved the path problem, but this problem occurs during operation, how can I solve it?

2019-12-12 18:13:20,058 - INFO - set log dir as ./logdir
2019-12-12 18:13:20,058 - INFO - set model dir as ./model
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
2019-12-12 18:13:53,441 - INFO - train_derain--l1_loss:0.008012 mask_loss:0.0927 ssim_loss:0.9782 all_loss:0.1225 lr:0.0005              step:4e+04
2019-12-12 18:13:54,780 - INFO - val_derain--l1_loss:0.007429 mask_loss:0.07181 ssim_loss:0.9779 all_loss:0.1013 lr:0.0005 s             tep:4e+04
2019-12-12 18:13:55,012 - INFO - save image as step_40000
2019-12-12 18:13:55,026 - INFO - save model as step_40000

**Comment by stevewongv** [comment]
> @stevewongv Thank you for your reply, I have solved the path problem, but this problem occurs during operation, how can I solve it?
> 
> 2019-12-12 18:13:20,058 - INFO - set log dir as ./logdir
> 2019-12-12 18:13:20,058 - INFO - set model dir as ./model
> THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
> THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
> THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
> THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
> 2019-12-12 18:13:53,441 - INFO - train_derain--l1_loss:0.008012 mask_loss:0.0927 ssim_loss:0.9782 all_loss:0.1225 lr:0.0005              step:4e+04
> 2019-12-12 18:13:54,780 - INFO - val_derain--l1_loss:0.007429 mask_loss:0.07181 ssim_loss:0.9779 all_loss:0.1013 lr:0.0005 s             tep:4e+04
> 2019-12-12 18:13:55,012 - INFO - save image as step_40000
> 2019-12-12 18:13:55,026 - INFO - save model as step_40000
> 

Which version of PyTorch are you using?

**Comment by FUNGERN** [comment]
0.4.1

**Comment by FUNGERN** [comment]
@stevewongv Can pytorch0.4.1 run on cuda9.0？

**Comment by stevewongv** [comment]
> @stevewongv Can pytorch0.4.1 run on cuda9.0？

Yes, but I did not meet this problem before. Please google this problem if you failed to train the model.

**Comment by FUNGERN** [comment]
ok, thanks

**Comment by FUNGERN** [comment]
Hello, I don't understand your paper. How do Rmin, Rmax and P^ understand it?
And I guess if it should be "> =" in Rmax equation?

**Comment by FUNGERN** [comment]
@stevewongv Hello, I don't understand your paper. How do Rmin, Rmax and P^ understand it?
And I guess if it should be "> =" in Rmax equation?

**Comment by stevewongv** [comment]
> @stevewongv Hello, I don't understand your paper. How do Rmin, Rmax and P^ understand it?
> And I guess if it should be "> =" in Rmax equation?

Yes, you are right. We had already fixed that in ArXiv: https://arxiv.org/pdf/1904.01538v2.pdf . Please check it out.

**Comment by FUNGERN** [comment]
@stevewongv very thank you，and I don't know how to better understand Rmin，Rmax and P^ , could you explain it for me ?

**Comment by stevewongv** [comment]
> @stevewongv very thank you，and I don't know how to better understand Rmin，Rmax and P^ , could you explain it for me ?

Please read the paper, I don’t have a lot of time to explain it just for you…

**Comment by FUNGERN** [comment]
@stevewongv Hi，Can you tell me what version of ptotobuf and tensorboard should be? I reinstalled the environment and encountered the following problem. The current error is that there is a problem with the protobuf version.

Traceback (most recent call last):
  File "main.py", line 16, in <module>
    from tensorboardX import SummaryWriter
  File "/home/pytor/.conda/envs/pytorh0.4.1/lib/python3.6/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from .torchvis import TorchVis
  File "/home/pytor/.conda/envs/pytorh0.4.1/lib/python3.6/site-packages/tensorboardX/torchvis.py", line 11, in <module>
    from .writer import SummaryWriter
  File "/home/pytor/.conda/envs/pytorh0.4.1/lib/python3.6/site-packages/tensorboardX/writer.py", line 15, in <module>
    from .event_file_writer import EventFileWriter
  File "/home/pytor/.conda/envs/pytorh0.4.1/lib/python3.6/site-packages/tensorboardX/event_file_writer.py", line 28, in <module>
    from .proto import event_pb2
  File "/home/pytor/.conda/envs/pytorh0.4.1/lib/python3.6/site-packages/tensorboardX/proto/event_pb2.py", line 16, in <module>
    from tensorboardX.proto import summary_pb2 as tensorboardX_dot_proto_dot_summary__pb2
  File "/home/pytor/.conda/envs/pytorh0.4.1/lib/python3.6/site-packages/tensorboardX/proto/summary_pb2.py", line 16, in <module>
    from tensorboardX.proto import tensor_pb2 as tensorboardX_dot_proto_dot_tensor__pb2
  File "/home/pytor/.conda/envs/pytorh0.4.1/lib/python3.6/site-packages/tensorboardX/proto/tensor_pb2.py", line 16, in <module>
    from tensorboardX.proto import resource_handle_pb2 as tensorboardX_dot_proto_dot_resource__handle__pb2
  File "/home/pytor/.conda/envs/pytorh0.4.1/lib/python3.6/site-packages/tensorboardX/proto/resource_handle_pb2.py", line 23, in <module>
    serialized_pb=_b('\n(tensorboardX/proto/resource_handle.proto\x12\x0ctensorboardX\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tB/\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01\xf8\x01\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'serialized_options'

**Comment by stevewongv** [comment]
Learn to search please... [Google](https://www.google.com/search?client=safari&rls=en&q=TypeError:+init()+got+an+unexpected+keyword+argument+%27serialized_options%27&ie=UTF-8&oe=UTF-8) [Baidu](https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&tn=baidu&wd=TypeError%3A%20init()%20got%20an%20unexpected%20keyword%20argument%20%27serialized_options%27&oq=Type%2526gt%253Brror%253A%252Binit()%252Bgot%252Ban%252Bunexpected%252Bkeyword%252Bargument%252B%2526%252339%253Bserialized_options%2526%252339%253B&rsv_pq=887528b70000870e&rsv_t=350bPk5bq6%2FFdQGNOKqOoU9Ma7kbn1c4qsLvAbv%2Bzwi3LANDYBy62fvxPGE&rqlang=cn&rsv_enter=1&rsv_dl=tb&rsv_sug2=0&inputT=26&rsv_sug4=26)
