### ISSUE TITLE
SAM 和 SAB

### ISSUE THREAD

**Issue by wushunshun** [stevewongv/SPANet#13]
作者您好，想要问您一个问题，关于您SAB模块的设计，是只算一次attention map，然后×bottleneck还是对SARB模块输出再重新计算一次attention map呢？

**Comment by stevewongv** [comment]
> 作者您好，想要问您一个问题，关于您SAB模块的设计，是只算一次attention map，然后×bottleneck还是对SARB模块输出再重新计算一次attention map呢？

里面的权重是共享的，每次会重新计算一个新的attention map, 因为之前一次已经去过一遍雨了，每次的map应该有些区别。
