### ISSUE TITLE
[dataset] some file format error

### ISSUE THREAD

**Issue by fly3366** [stevewongv/SPANet#15]
![image](https://user-images.githubusercontent.com/38378045/79215183-d7843900-7e7d-11ea-85ff-d7091d807ac9.png)
like this.... may file-program has some hack?

**Comment by stevewongv** [comment]
Thank you for using our dataset.

Just use the txt file (called **real_world.txt**) to load data if you have downloaded the latest version of the dataset!

**Comment by Jack10001** [comment]
for example, just unpack  "real_world.zip.001" and set "real_world" dir under "SPANet" dir, then run SPANET.py. Am I right?

**Comment by stevewongv** [comment]
> for example, just unpack  "real_world.zip.001" and set "real_world" dir under "SPANet" dir, then run SPANET.py. Am I right?

Wrong. You must download all dataset files for training and use main.py. Please follow the README.

**Comment by Jack10001** [comment]
OK, Thank you!

Steve Wong <notifications@github.com> 于2020年4月17日周五 下午8:46写道：
