### ISSUE TITLE
 the structure of  Percentile filter

### ISSUE THREAD

**Issue by jilner** [stevewongv/SPANet#3]
Thanks for the great repo.
The paper didn't tell the Percentile filter in detail,could you release the code of Percentile filter,or tell us the theory of  Percentile filter. Thanks again.

**Comment by stevewongv** [comment]
I can give you two links which may help you:
* [numpy.percentile](http://docs.scipy.org/doc/numpy-1.16.1/reference/generated/numpy.percentile.html#numpy.percentile)
* [Percentile](https://en.wikipedia.org/wiki/Percentile)
