### ISSUE TITLE
模型加载

### ISSUE THREAD

**Issue by jilner** [stevewongv/SPANet#5]
作者您好，我在测试的时候模型加载没问题，但是当训练的时候加载报错，加载net没问题，加载优化函数Adam报错self.opt.load_state_dict(obj['opt']) ，报错，loaded state dict contains a parameter group that doesn't match the size of optimizer's group

**Comment by stevewongv** [comment]
请新建一个model文件再重新训练。训练其他数据集，请保证mask有效。
