### ISSUE TITLE
libpng error: Read Error 

### ISSUE THREAD

**Issue by jifenghu** [stevewongv/SPANet#6]
Hi ~
Thanks to share this model ~ And I run this model with error like 
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/33339682/57600751-4467c280-758d-11e9-87ac-6b8406613885.png">

how can I solve this ?   Thank you ~

**Comment by stevewongv** [comment]
It seems like TensorboardX's problem. I haven't come across this before. And you can google for this problem.
